# globals.py

# SCREEN_SIZE
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

# HIT_ANIMATION
TIME_PER_HIT_ANIMATION = 0.2
HIT_ANIMATION_PER_TIME = 1.0 / TIME_PER_HIT_ANIMATION
FRAME_PER_HIT_ANIMATION = 8

# CHARACTER_ANIMATION
TIME_PER_CHARACTER_ANIMATION = 0.3
CHARACTER_ANIMATION_PER_TIME = 1.0 / TIME_PER_CHARACTER_ANIMATION
FRAME_PER_CHARACTER_ANIMATION = 8

# ATTACK_ANIMATION
TIME_PER_ATTACK_ANIMATION = 0.3
ATTACK_ANIMATION_PER_TIME = 1.0 / TIME_PER_ATTACK_ANIMATION
FRAME_PER_ATTACK_ANIMATION = 8

# mouse_position
mouse_x = 0
mouse_y = 0


